url: "http://deprogramming.radio" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Radio Deprogramming"
permalink: /:categories/:title:output_ext

collections:
  deprogramming:
    output: true
  meeting:
    output: true
  listening:
    output: false
  reading:
    output: false
  quotes:
    output: false
