url: "https://akstuhl.net" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/deprogramming" # the subpath of your site, e.g. /blog
title: "Radio Deprogramming"

collections:
  deprogramming:
    output: true
  meeting:
    output: true
    sort_by: pin
  listening:
    output: false
    sort_by: year
  reading:
    output: false
  quotes:
    output: false
